mkdir -p ~/ros/accompany/accompany_static_camera_localisation/res/new_background_images

mkdir -p ~/ros/accompany/accompany_static_camera_localisation/res/background_images

roslaunch accompany_static_camera_localisation kinect_capture_background_images.launch
