"""autogenerated by genpy from accompany_uva_msg/Appearance.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Appearance(genpy.Message):
  _md5sum = "bd36eb66e6a8febafac79f820b94b7e8"
  _type = "accompany_uva_msg/Appearance"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32      sumTemplatePixelSize
float64    sumPixelWeights
float64[]  histogram

"""
  __slots__ = ['sumTemplatePixelSize','sumPixelWeights','histogram']
  _slot_types = ['int32','float64','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sumTemplatePixelSize,sumPixelWeights,histogram

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Appearance, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.sumTemplatePixelSize is None:
        self.sumTemplatePixelSize = 0
      if self.sumPixelWeights is None:
        self.sumPixelWeights = 0.
      if self.histogram is None:
        self.histogram = []
    else:
      self.sumTemplatePixelSize = 0
      self.sumPixelWeights = 0.
      self.histogram = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_id.pack(_x.sumTemplatePixelSize, _x.sumPixelWeights))
      length = len(self.histogram)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.histogram))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.sumTemplatePixelSize, _x.sumPixelWeights,) = _struct_id.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.histogram = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_id.pack(_x.sumTemplatePixelSize, _x.sumPixelWeights))
      length = len(self.histogram)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.histogram.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.sumTemplatePixelSize, _x.sumPixelWeights,) = _struct_id.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.histogram = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_id = struct.Struct("<id")
