"""autogenerated by genpy from accompany_uva_msg/HumanDetection.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import accompany_uva_msg.msg
import std_msgs.msg

class HumanDetection(genpy.Message):
  _md5sum = "2f5bd75e42cea1d99d835a2e15ac1849"
  _type = "accompany_uva_msg/HumanDetection"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/PointStamped location
Appearance appearance

================================================================================
MSG: geometry_msgs/PointStamped
# This represents a Point with reference coordinate frame and timestamp
Header header
Point point

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: accompany_uva_msg/Appearance
int32      sumTemplatePixelSize
float64    sumPixelWeights
float64[]  histogram

"""
  __slots__ = ['location','appearance']
  _slot_types = ['geometry_msgs/PointStamped','accompany_uva_msg/Appearance']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       location,appearance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HumanDetection, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.location is None:
        self.location = geometry_msgs.msg.PointStamped()
      if self.appearance is None:
        self.appearance = accompany_uva_msg.msg.Appearance()
    else:
      self.location = geometry_msgs.msg.PointStamped()
      self.appearance = accompany_uva_msg.msg.Appearance()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.location.header.seq, _x.location.header.stamp.secs, _x.location.header.stamp.nsecs))
      _x = self.location.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3did.pack(_x.location.point.x, _x.location.point.y, _x.location.point.z, _x.appearance.sumTemplatePixelSize, _x.appearance.sumPixelWeights))
      length = len(self.appearance.histogram)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.pack(pattern, *self.appearance.histogram))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.location is None:
        self.location = geometry_msgs.msg.PointStamped()
      if self.appearance is None:
        self.appearance = accompany_uva_msg.msg.Appearance()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.location.header.seq, _x.location.header.stamp.secs, _x.location.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.location.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.location.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.location.point.x, _x.location.point.y, _x.location.point.z, _x.appearance.sumTemplatePixelSize, _x.appearance.sumPixelWeights,) = _struct_3did.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.appearance.histogram = struct.unpack(pattern, str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.location.header.seq, _x.location.header.stamp.secs, _x.location.header.stamp.nsecs))
      _x = self.location.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3did.pack(_x.location.point.x, _x.location.point.y, _x.location.point.z, _x.appearance.sumTemplatePixelSize, _x.appearance.sumPixelWeights))
      length = len(self.appearance.histogram)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.appearance.histogram.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.location is None:
        self.location = geometry_msgs.msg.PointStamped()
      if self.appearance is None:
        self.appearance = accompany_uva_msg.msg.Appearance()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.location.header.seq, _x.location.header.stamp.secs, _x.location.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.location.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.location.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 36
      (_x.location.point.x, _x.location.point.y, _x.location.point.z, _x.appearance.sumTemplatePixelSize, _x.appearance.sumPixelWeights,) = _struct_3did.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      end += struct.calcsize(pattern)
      self.appearance.histogram = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_3did = struct.Struct("<3did")
