(cl:defpackage accompany_uva_msg-msg
  (:use )
  (:export
   "<TRACKEDHUMAN>"
   "TRACKEDHUMAN"
   "<TRACKEDHUMANS>"
   "TRACKEDHUMANS"
   "<APPEARANCE>"
   "APPEARANCE"
   "<HUMANLOCATIONSPARTICLES>"
   "HUMANLOCATIONSPARTICLES"
   "<HUMANLOCATIONSPARTICLE>"
   "HUMANLOCATIONSPARTICLE"
   "<HUMANLOCATIONS>"
   "HUMANLOCATIONS"
   "<HUMANDETECTION>"
   "HUMANDETECTION"
   "<HUMANDETECTIONS>"
   "HUMANDETECTIONS"
  ))

