/* Auto-generated by genmsg_cpp for file /home/accompany/git/accompany/accompany_uva_msg/msg/HumanDetection.msg */
#ifndef ACCOMPANY_UVA_MSG_MESSAGE_HUMANDETECTION_H
#define ACCOMPANY_UVA_MSG_MESSAGE_HUMANDETECTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PointStamped.h"
#include "accompany_uva_msg/Appearance.h"

namespace accompany_uva_msg
{
template <class ContainerAllocator>
struct HumanDetection_ {
  typedef HumanDetection_<ContainerAllocator> Type;

  HumanDetection_()
  : location()
  , appearance()
  {
  }

  HumanDetection_(const ContainerAllocator& _alloc)
  : location(_alloc)
  , appearance(_alloc)
  {
  }

  typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _location_type;
   ::geometry_msgs::PointStamped_<ContainerAllocator>  location;

  typedef  ::accompany_uva_msg::Appearance_<ContainerAllocator>  _appearance_type;
   ::accompany_uva_msg::Appearance_<ContainerAllocator>  appearance;


  typedef boost::shared_ptr< ::accompany_uva_msg::HumanDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accompany_uva_msg::HumanDetection_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HumanDetection
typedef  ::accompany_uva_msg::HumanDetection_<std::allocator<void> > HumanDetection;

typedef boost::shared_ptr< ::accompany_uva_msg::HumanDetection> HumanDetectionPtr;
typedef boost::shared_ptr< ::accompany_uva_msg::HumanDetection const> HumanDetectionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::accompany_uva_msg::HumanDetection_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::accompany_uva_msg::HumanDetection_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace accompany_uva_msg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::accompany_uva_msg::HumanDetection_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::accompany_uva_msg::HumanDetection_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::accompany_uva_msg::HumanDetection_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2f5bd75e42cea1d99d835a2e15ac1849";
  }

  static const char* value(const  ::accompany_uva_msg::HumanDetection_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2f5bd75e42cea1d9ULL;
  static const uint64_t static_value2 = 0x9d835a2e15ac1849ULL;
};

template<class ContainerAllocator>
struct DataType< ::accompany_uva_msg::HumanDetection_<ContainerAllocator> > {
  static const char* value() 
  {
    return "accompany_uva_msg/HumanDetection";
  }

  static const char* value(const  ::accompany_uva_msg::HumanDetection_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::accompany_uva_msg::HumanDetection_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/PointStamped location\n\
Appearance appearance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: accompany_uva_msg/Appearance\n\
int32      sumTemplatePixelSize\n\
float64    sumPixelWeights\n\
float64[]  histogram\n\
\n\
";
  }

  static const char* value(const  ::accompany_uva_msg::HumanDetection_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::accompany_uva_msg::HumanDetection_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.location);
    stream.next(m.appearance);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HumanDetection_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accompany_uva_msg::HumanDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::accompany_uva_msg::HumanDetection_<ContainerAllocator> & v) 
  {
    s << indent << "location: ";
s << std::endl;
    Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.location);
    s << indent << "appearance: ";
s << std::endl;
    Printer< ::accompany_uva_msg::Appearance_<ContainerAllocator> >::stream(s, indent + "  ", v.appearance);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ACCOMPANY_UVA_MSG_MESSAGE_HUMANDETECTION_H

