/* Auto-generated by genmsg_cpp for file /home/accompany/git/accompany/accompany_uva_msg/msg/HumanLocations.msg */
#ifndef ACCOMPANY_UVA_MSG_MESSAGE_HUMANLOCATIONS_H
#define ACCOMPANY_UVA_MSG_MESSAGE_HUMANLOCATIONS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PointStamped.h"

namespace accompany_uva_msg
{
template <class ContainerAllocator>
struct HumanLocations_ {
  typedef HumanLocations_<ContainerAllocator> Type;

  HumanLocations_()
  : locations()
  {
  }

  HumanLocations_(const ContainerAllocator& _alloc)
  : locations(_alloc)
  {
  }

  typedef std::vector< ::geometry_msgs::PointStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PointStamped_<ContainerAllocator> >::other >  _locations_type;
  std::vector< ::geometry_msgs::PointStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PointStamped_<ContainerAllocator> >::other >  locations;


  typedef boost::shared_ptr< ::accompany_uva_msg::HumanLocations_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accompany_uva_msg::HumanLocations_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HumanLocations
typedef  ::accompany_uva_msg::HumanLocations_<std::allocator<void> > HumanLocations;

typedef boost::shared_ptr< ::accompany_uva_msg::HumanLocations> HumanLocationsPtr;
typedef boost::shared_ptr< ::accompany_uva_msg::HumanLocations const> HumanLocationsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::accompany_uva_msg::HumanLocations_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::accompany_uva_msg::HumanLocations_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace accompany_uva_msg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::accompany_uva_msg::HumanLocations_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::accompany_uva_msg::HumanLocations_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::accompany_uva_msg::HumanLocations_<ContainerAllocator> > {
  static const char* value() 
  {
    return "048149b61e4930bb4c889d2870736e2c";
  }

  static const char* value(const  ::accompany_uva_msg::HumanLocations_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x048149b61e4930bbULL;
  static const uint64_t static_value2 = 0x4c889d2870736e2cULL;
};

template<class ContainerAllocator>
struct DataType< ::accompany_uva_msg::HumanLocations_<ContainerAllocator> > {
  static const char* value() 
  {
    return "accompany_uva_msg/HumanLocations";
  }

  static const char* value(const  ::accompany_uva_msg::HumanLocations_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::accompany_uva_msg::HumanLocations_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/PointStamped[] locations\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::accompany_uva_msg::HumanLocations_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::accompany_uva_msg::HumanLocations_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.locations);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HumanLocations_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accompany_uva_msg::HumanLocations_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::accompany_uva_msg::HumanLocations_<ContainerAllocator> & v) 
  {
    s << indent << "locations[]" << std::endl;
    for (size_t i = 0; i < v.locations.size(); ++i)
    {
      s << indent << "  locations[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.locations[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ACCOMPANY_UVA_MSG_MESSAGE_HUMANLOCATIONS_H

