/* Auto-generated by genmsg_cpp for file /home/accompany/git/accompany/accompany_uva_msg/msg/HumanLocationsParticle.msg */
#ifndef ACCOMPANY_UVA_MSG_MESSAGE_HUMANLOCATIONSPARTICLE_H
#define ACCOMPANY_UVA_MSG_MESSAGE_HUMANLOCATIONSPARTICLE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PointStamped.h"

namespace accompany_uva_msg
{
template <class ContainerAllocator>
struct HumanLocationsParticle_ {
  typedef HumanLocationsParticle_<ContainerAllocator> Type;

  HumanLocationsParticle_()
  : locations()
  , weight(0.0)
  {
  }

  HumanLocationsParticle_(const ContainerAllocator& _alloc)
  : locations(_alloc)
  , weight(0.0)
  {
  }

  typedef std::vector< ::geometry_msgs::PointStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PointStamped_<ContainerAllocator> >::other >  _locations_type;
  std::vector< ::geometry_msgs::PointStamped_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::PointStamped_<ContainerAllocator> >::other >  locations;

  typedef float _weight_type;
  float weight;


  typedef boost::shared_ptr< ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HumanLocationsParticle
typedef  ::accompany_uva_msg::HumanLocationsParticle_<std::allocator<void> > HumanLocationsParticle;

typedef boost::shared_ptr< ::accompany_uva_msg::HumanLocationsParticle> HumanLocationsParticlePtr;
typedef boost::shared_ptr< ::accompany_uva_msg::HumanLocationsParticle const> HumanLocationsParticleConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace accompany_uva_msg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "349a944ee281c735fe6b84bd25a7f2b1";
  }

  static const char* value(const  ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x349a944ee281c735ULL;
  static const uint64_t static_value2 = 0xfe6b84bd25a7f2b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "accompany_uva_msg/HumanLocationsParticle";
  }

  static const char* value(const  ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/PointStamped[] locations\n\
float32 weight\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.locations);
    stream.next(m.weight);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HumanLocationsParticle_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::accompany_uva_msg::HumanLocationsParticle_<ContainerAllocator> & v) 
  {
    s << indent << "locations[]" << std::endl;
    for (size_t i = 0; i < v.locations.size(); ++i)
    {
      s << indent << "  locations[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.locations[i]);
    }
    s << indent << "weight: ";
    Printer<float>::stream(s, indent + "  ", v.weight);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ACCOMPANY_UVA_MSG_MESSAGE_HUMANLOCATIONSPARTICLE_H

