/* Auto-generated by genmsg_cpp for file /home/accompany/git/accompany/accompany_uva_msg/msg/TrackedHumans.msg */
#ifndef ACCOMPANY_UVA_MSG_MESSAGE_TRACKEDHUMANS_H
#define ACCOMPANY_UVA_MSG_MESSAGE_TRACKEDHUMANS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "accompany_uva_msg/TrackedHuman.h"

namespace accompany_uva_msg
{
template <class ContainerAllocator>
struct TrackedHumans_ {
  typedef TrackedHumans_<ContainerAllocator> Type;

  TrackedHumans_()
  : trackedHumans()
  {
  }

  TrackedHumans_(const ContainerAllocator& _alloc)
  : trackedHumans(_alloc)
  {
  }

  typedef std::vector< ::accompany_uva_msg::TrackedHuman_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::accompany_uva_msg::TrackedHuman_<ContainerAllocator> >::other >  _trackedHumans_type;
  std::vector< ::accompany_uva_msg::TrackedHuman_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::accompany_uva_msg::TrackedHuman_<ContainerAllocator> >::other >  trackedHumans;


  typedef boost::shared_ptr< ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::accompany_uva_msg::TrackedHumans_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct TrackedHumans
typedef  ::accompany_uva_msg::TrackedHumans_<std::allocator<void> > TrackedHumans;

typedef boost::shared_ptr< ::accompany_uva_msg::TrackedHumans> TrackedHumansPtr;
typedef boost::shared_ptr< ::accompany_uva_msg::TrackedHumans const> TrackedHumansConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace accompany_uva_msg

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::accompany_uva_msg::TrackedHumans_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> > {
  static const char* value() 
  {
    return "a6569de3725dc368e6c9805c323491a3";
  }

  static const char* value(const  ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xa6569de3725dc368ULL;
  static const uint64_t static_value2 = 0xe6c9805c323491a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> > {
  static const char* value() 
  {
    return "accompany_uva_msg/TrackedHumans";
  }

  static const char* value(const  ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> > {
  static const char* value() 
  {
    return "accompany_uva_msg/TrackedHuman[] trackedHumans\n\
\n\
================================================================================\n\
MSG: accompany_uva_msg/TrackedHuman\n\
geometry_msgs/PointStamped location\n\
geometry_msgs/Vector3Stamped speed\n\
int32 id\n\
string identity\n\
time firstSeen\n\
time lastSeen\n\
int32 specialFlag\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3Stamped\n\
# This represents a Vector3 with reference coordinate frame and timestamp\n\
Header header\n\
Vector3 vector\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.trackedHumans);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct TrackedHumans_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::accompany_uva_msg::TrackedHumans_<ContainerAllocator> & v) 
  {
    s << indent << "trackedHumans[]" << std::endl;
    for (size_t i = 0; i < v.trackedHumans.size(); ++i)
    {
      s << indent << "  trackedHumans[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::accompany_uva_msg::TrackedHuman_<ContainerAllocator> >::stream(s, indent + "    ", v.trackedHumans[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ACCOMPANY_UVA_MSG_MESSAGE_TRACKEDHUMANS_H

