(cl:defpackage AccompanyService-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "DB_MSG"
   "<DB_MSG-REQUEST>"
   "DB_MSG-REQUEST"
   "<DB_MSG-RESPONSE>"
   "DB_MSG-RESPONSE"
   "ACCOMPANYACTION"
   "<ACCOMPANYACTION-REQUEST>"
   "ACCOMPANYACTION-REQUEST"
   "<ACCOMPANYACTION-RESPONSE>"
   "ACCOMPANYACTION-RESPONSE"
  ))

