# Squares the input number and returns the result
#
# request message
float64 number		# the number which shall be squared, see www.ros.org for other data types available
---
# response message
float64 numberSquared	# the square of number
